# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
resource "google_compute_network" "vpc" {
  name                    = "gleb-dev-vpc"
  auto_create_subnetworks = false
  routing_mode            = "REGIONAL"
}

resource "google_compute_subnetwork" "primary" {
  name                     = "primary"
  ip_cidr_range            = "10.100.0.0/20"
  region                   = "us-east1"
  network                  = google_compute_network.vpc.id
  private_ip_google_access = true

  secondary_ip_range {
    range_name    = "primary-pods"
    ip_cidr_range = "10.104.0.0/14"
  }
  secondary_ip_range {
    range_name    = "primary-services"
    ip_cidr_range = "192.168.0.0/20"
  }
}

output "network_name" { value = google_compute_network.vpc.name }
output "network_self_link" { value = google_compute_network.vpc.self_link }
output "subnets_names" { value = [google_compute_subnetwork.primary.name] }
